### PR TITLE
Monikas review plotting post

### PR DESCRIPTION
**Pull request by MonikaFu**
In this PR I add my proposed changes to the article written by @georgeharris2deg. This is still subject to his approval so please, don't merge yet!

### CODE REVIEW

**Review by maurolepore — APPROVED** [review]
LGTM

**Comment by MonikaFu** [comment]
@maurolepore my changes are approved by @georgeharris2deg. How do we proceed from here to post the article on the blog with a recent date?

**Comment by maurolepore** [comment]
Thanks! From here I take over. The article is now listed near the top of the blog's front page, next to the other post we recently worked on:

https://2degreesinvesting.github.io/

image

**Comment by MonikaFu** [comment]
Should I close this PR now without merging @maurolepore? Since the blog is published.

**Pull request merged**
