### PR TITLE
fix pr 5

### PR DESCRIPTION
**Pull request by maurolepore**

### CODE REVIEW

**Comment by maurolepore** [comment]
@vintented, this PR is the same as #5 but with a clean commit history and no merge conflicts. Can you check it contains all the changes you expect? 

Best would be for you to build it locally and see the .html output is as you expect. You may do this in a number of ways:

* Use your favorite git client.
* Use the PR helpers from the usethis package: https://usethis.r-lib.org/reference/pull-requests.html
* Follow the command line instructions that GitHub provides:

image


If you need to add changes, you may need to first accept my invitation to collaborate on my fork:
https://github.com/maurolepore/2degreesinvesting.github.io/invitations

**Review by vintented — APPROVED** [review]
Looks great, thanks!

**Comment by vintented** [comment]
@maurolepore once I have built/knitted the html should I pushed the committed output?

**Comment by maurolepore** [comment]
No need to push. If what you say is okay, then I'll merge this PR now; you'll see the result reflected on the blog in a few minutes.

**Comment by maurolepore** [comment]
Enjoy: https://2degreesinvesting.github.io/posts/2020-07-24-when-scenarios-and-reality-diverge/

**Pull request merged**
