### PR TITLE
r2dii.plot 0.2.0

### PR DESCRIPTION
**Pull request by maurolepore**
@MonikaFu I wrote a lil post about r2dii.plot 0.2.0. I guess you won't see it and I think it's fine. But I thought of just letting you know. We can tweak it when you're back to work. For now I plan to use this as is for an internal announcement on the `#coding` channel on our slack.

### CODE REVIEW

**Review by MonikaFu — APPROVED** [review]
Hi Mauro. The article is great. I don't see any reason to tweak it further :) LGTM

**Comment by MonikaFu** [comment]
@maurolepore do we know why we never posted this one??

**Comment by maurolepore** [comment]
I guess I just forgot? I'll fix merge conflicts and publish.

**Comment by maurolepore** [comment]
The post is now published at https://2degreesinvesting.github.io/posts/2021-10-18-r2dii-plot-0-2-0/

I think the issue is what I forgot to change `draft: true` to `false`.

**Pull request merged**
