### PR TITLE
use flatly theme

### PR DESCRIPTION
**Pull request by jdhoffa**
I went ahead and tried to re-format the website a little bit to suit more the `flatly` theme used in the `r2dii.*` package websites (e.g. https://2degreesinvesting.github.io/r2dii.data/ ). 

Not sure if everything I changed is necessary (and also, I couldn't figure out how to increase the font size on the About page), but have a look and let me know what you guys think!

In particular, @vintented I'd like if you could have a look since you put so much work into developing those `.Rmd` templates.

### CODE REVIEW

**Comment by jdhoffa** [comment]
Also note, this PR touches a lot of files, but the key commits are to the .css file, as well as some formatting changes and addition of logos/ favicons. 

The rest of the changes are just noise in the `.html` files when they were re-built.

**Comment by maurolepore** [comment]
Awesome! I love you managed to add the logo. I tried a while ago but failed to sized it in an appealing way.

image

If you are happy with it, go ahead and merge.

**Review by maurolepore — APPROVED** [review]

**Comment by jdhoffa** [comment]
I think it could use a few more tweaks, but honestly I think I could tweak it forever, so maybe lets merge it for now, and I'll come back to it later!

**Comment by vintented** [comment]
@jdhoffa looks awesome!

**Pull request merged**
