### PR TITLE
Add new market share blog post

### PR DESCRIPTION
**Pull request by jdhoffa**
First draft of a blog post giving a comprehensive breakdown of the different target setting methodologies, and the potential issues that arise with interpretation and plotting. 

@maurolepore I leave it as a draft for now, since I'm not sure I want to merge it as-is, but I want it to be open here for people to proof-read.

### CODE REVIEW

**Comment by maurolepore** [comment]
Sounds good. 

Do your proof-readers prefer the .html version? If so one hack I've used is to publish it but make it hard to discover, e.g. by using an old date and using no category.

Note the [checklist to publish a new post](https://github.com/2DegreesInvesting/2degreesinvesting.github.io/blob/master/README.md#checklist-to-publish-a-new-post).

**Comment by jdhoffa** [comment]
> Sounds good.
> 
> Do your proof-readers prefer the .html version? If so one hack I've used is to publish it but make it hard to discover, e.g. by using an old date and using no category.
> 
> Note the [checklist to publish a new post](https://github.com/2DegreesInvesting/2degreesinvesting.github.io/blob/master/README.md#checklist-to-publish-a-new-post).

So this workflow doesn't work for me for some reason. I can spin up the docker container, and open RStudio, but when I log-in, it says it is unable to open RStudio.

**Comment by maurolepore** [comment]
Uh, so user: rstudio and password: 123 doesn't drop you into a functional rstudio session? Weird. Can you share some detail to see if I can help? Maybe a  message or screenshoot here, or video -capture on slack?

**Comment by jdhoffa** [comment]
So, after running `docker-compose up`, my console outputs this:
Screenshot 2022-04-25 at 21 02 29

When I navigate to http://localhost:8787/ I get this: 
Screenshot 2022-04-25 at 21 04 02

What's interesting is the last time I ran the container, I was able to get to a log-in screen, and this time I don't even see that. It's very odd that running the same container with the same parameters would lead to different results?

**Comment by maurolepore** [comment]
Weird indeed. Something in the container or RStudio server seems to be corrupt. 

How about removing the relevant images `maurolepore/2dii_blog:0.0.0` and `rocker/verse:3.6`? Then `docker-compose up` should pull fresh images from dockerhub. 

If that fails we could try these things:

* Reproduce [this](https://github.com/2DegreesInvesting/2degreesinvesting.github.io/blob/master/Dockerfile) in some other way.

* Understand why a new version of distill fails and fix it. I tried to do this before but I don't remember what the problem was and I guess I decided it was not worth to get to the bottom of the problem.

* Change the blog framework to something more robust. Do you have a favorite one?




https://github.com/2DegreesInvesting/2degreesinvesting.github.io/blob/master/Dockerfile

**Pull request merged**
