### PR TITLE
V2 of first blog post 

### PR DESCRIPTION
**Pull request by vintented**

### CODE REVIEW

**Comment by maurolepore** [comment]
@vintented, here is a comment (not about content but) about your workflow. You did great in submitting your PRs (#4 and #5) from your fork. But you forgot to do it from a "feature" branch. No big deal -- I'll fix that on your behalf. But I know you are curious and keen to use best practices, so I'll explain what the problem is so next time you can avoid it.

In general, try to use the [GitHub flow](https://guides.github.com/introduction/flow/). That is, [avoid submitting pull requests from your master branch; instead submit them from a dedicated, "feature" branch](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/). 

The first time you submit a PR there is not problem. But the second time you submit a PR you may end up with a mess because the history of the master branch on upstream (upstream/master) is likely different from the history of the master branch on your fork (origin/master): All commits in any PR are commonly squashed into a single commit that tell the story of the PR more clearly; and any new commits added to upsream/master will not be reflected in your origin/master.

Let's make this concrete with an example from this PR.

Since I merged your PR #4, I added new commits to upstream/master that your for lacks:

image

This causes a bit of a mess: The changes from your first PR #4 (that I squash-merged into upstream/master) still show up on your second PR #5:

image

Instead, your second PR #5 should only have these commits:

image

What I'll do is this:

* Fetch your PR #5 locally.
* Pull the new, relevant commits (from 1d4cccc to 75f65c7).
* Close this PR.
* Submit a pull request from my fork and ask you to review it.

**Comment by maurolepore** [comment]
See #6

**Comment by vintented** [comment]
@maurolepore thank you and sorry about the hassle. I guess I have been working too long in my own coding bubble without any need for git. It looks like I am a tad rusty, but thanks for your patience. I will check out the resources you shared and the new pull request.

**Comment by maurolepore** [comment]
No problem at all. I was in the same position only a short time ago. It's something that comes only with practice.

**Pull request closed without merging**
